#!/bin/sh /etc/rc.common

USE_PROCD=1
START=95
STOP=01

start_service() {
    procd_open_instance
    # Hold SIM7070G power key at 0
    procd_set_param command gpioset -c0 4=0
    procd_close_instance
}
